dbt_project:
  outputs:
    dev:
      type: duckdb
      path: ./data/warehouse/dev.duckdb
      threads: 1

    prod:
      type: duckdb
      path: ./data/warehouse/prod.duckdb
      threads: 4

  target: dev
